services:
  - type: web
    name: retail-agent-fastapi
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9   # ðŸ‘ˆ force Python 3.11
      - key: AZ_SQL_SERVER
        sync: false
      - key: AZ_SQL_DB
        sync: false
      - key: AZ_SQL_USER
        sync: false
      - key: AZ_SQL_PASSWORD
        sync: false
